name: tmgdroid
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  flutter_secure_storage: ^9.2.2
  get_it: ^7.7.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/images/prg.png

flutter:
  uses-material-design: true
